name: CI
on: [pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Install server
        working-directory: ./server
        run: yarn install --frozen-lockfile
      - name: Run server tests
        working-directory: ./server
        run: yarn test
  build-and-test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Install client
        working-directory: ./client
        run: yarn install --frozen-lockfile
      - name: Run client tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./client
          build: yarn build
          start: yarn start
